name: compiler
author: Chris Bacon & Jacob Clark
github: exosphere-lang/compiler
license: MIT
copyright: 2019 Chris Bacon & Jacob Clark
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
description: Please see the README on GitHub at <https://github.com/exosphere/compiler#readme>

dependencies:
- base
- aeson
- bytestring

executables:
  exospherec:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - compiler

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-incomplete-patterns
  dependencies:
  - parsec
  - split
  - containers
  - text
  - unordered-containers

tests:
  exosphere-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-incomplete-patterns
    dependencies:
    - compiler
    - hspec
