library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - parsec
  - split
  - containers
  - aeson
  - bytestring
tests:
  exosphere-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bytestring
    - compiler
    - hspec
    - aeson
copyright: 2019 Chris Bacon & Jacob Clark
dependencies:
- base >= 4.7 && < 5
name: compiler
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Chris Bacon & Jacob Clark
github: exosphere-lang/compiler
license: MIT
executables:
  compiler:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - compiler
description: Please see the README on GitHub at <https://github.com/exosphere/compiler#readme>
